/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.region.view;

import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.DefaultListModel;

import br.com.region.model.estado.EstadoModel;
import br.com.region.model.municipio.MunicipioModel;

import br.com.region.service.IbgeService;

import br.com.region.view.municipio.MunicipioModal;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luiz_
 */
public final class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    private List<EstadoModel> estados;
    private List<MunicipioModel> municipios;
    
    private static final Logger logger = Logger.getLogger(MainScreen.class.getName());
    
    public MainScreen() {
        setTitle("UF e Municípios");
        setResizable(false);
        initComponents();
        initPropertys();
        initLoadingComponent();
    }
    
    private void centralizeScreen() {
        this.setLocationRelativeTo(null);
    }
    
    private void initLoadingComponent(){
        
        jpLoading.setVisible(false);
        
        ImageIcon icon = new ImageIcon("C:\\Users\\Luiz_\\OneDrive\\Área de Trabalho\\icons8-spinner.gif");
        icon.setImage( icon.getImage().getScaledInstance( lblLoading.getWidth(),lblLoading.getHeight() , 1));
        
        lblLoading.setIcon( icon );
        
    }
    
    private void onMunicipioSelected( final MunicipioModel municipio ) {

        MunicipioModal municipioModal = new MunicipioModal( this, true, municipio );
        municipioModal.setVisible(true);

    }
    
    private void onEstadoChanged(){
        
        String currentUF = estados.get(cbUfs.getSelectedIndex()).getSigla();
        
        IbgeService ibgeService = new IbgeService();
        
        jLblTextLoading.setText("Buscando municipios...");

        try {
            
            Thread thread = new Thread( () -> {

                jlpInformations.setVisible(false);
                jpLoading.setVisible(true);
                btnSearch.setEnabled(false);
                cbUfs.setEnabled(false);

                municipios = ibgeService.findMunicipiosByUF( currentUF );
                listMunicipios.setModel( municipiosToListModel( municipios ) );

                cbUfs.setEnabled(true);
                btnSearch.setEnabled(true);
                jpLoading.setVisible(false);
                jlpInformations.setVisible(true);

            } );
                
            thread.start();
            
        } catch ( Exception e ) {
            logger.log(Level.SEVERE, "onEstadoChanged, Erro capturado [WHAT] {0}", e.getMessage());
        }
        

    }
    
    private DefaultListModel<String> municipiosToListModel( final List<MunicipioModel> municipios  ){
    
        DefaultListModel<String> listModel = new DefaultListModel<>();
        
        municipios.forEach( ( current ) -> {
            listModel.insertElementAt( current.getNome() , municipios.indexOf(current) );
        } );
        
        return listModel;
        
    }
    
    private void estadosToComboBoxScreen() {
        
        try {
            
            IbgeService ibgeService = new IbgeService();
            estados = ibgeService.findEstados();                

            estados.forEach( ( current ) -> {
                cbUfs.insertItemAt( current.getNome(), estados.indexOf(current) );
            } );

            cbUfs.setSelectedIndex(0); 
            
        } catch ( Exception e ) {
            logger.log(Level.SEVERE, "estadosToComboBoxScreen, Erro capturado [WHAT] {0}", e.getMessage());
        }
        
    }
    
    private void initPropertys(){
        centralizeScreen();
        estadosToComboBoxScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jpMain = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        cbUfs = new javax.swing.JComboBox<>();
        lblUf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlpInformations = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMunicipios = new javax.swing.JList<>();
        lblMunicipios = new javax.swing.JLabel();
        jpLoading = new javax.swing.JPanel();
        lblLoading = new javax.swing.JLabel();
        jLblTextLoading = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 153));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(1062, 448));
        jPanel1.setPreferredSize(new java.awt.Dimension(1029, 471));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jpMain.setBackground(new java.awt.Color(255, 255, 255));

        btnSearch.setBackground(new java.awt.Color(102, 204, 255));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Buscar");
        btnSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSearch.setBorderPainted(false);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        lblUf.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblUf.setText("UF");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel2.setText("Visualizador de municípios");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setInheritsPopupMenu(true);
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(1003, 268));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jlpInformations.setBackground(new java.awt.Color(255, 255, 255));
        jlpInformations.setForeground(new java.awt.Color(255, 255, 255));
        jlpInformations.setMaximumSize(new java.awt.Dimension(400, 400));

        listMunicipios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMunicipiosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listMunicipios);

        lblMunicipios.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMunicipios.setText("Municípios");
        lblMunicipios.setToolTipText("");

        jlpInformations.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpInformations.setLayer(lblMunicipios, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpInformationsLayout = new javax.swing.GroupLayout(jlpInformations);
        jlpInformations.setLayout(jlpInformationsLayout);
        jlpInformationsLayout.setHorizontalGroup(
            jlpInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpInformationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMunicipios)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpInformationsLayout.setVerticalGroup(
            jlpInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpInformationsLayout.createSequentialGroup()
                .addComponent(lblMunicipios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jlpInformations, gridBagConstraints);

        jpLoading.setBackground(new java.awt.Color(255, 255, 255));

        lblLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLblTextLoading.setText("loading...");

        javax.swing.GroupLayout jpLoadingLayout = new javax.swing.GroupLayout(jpLoading);
        jpLoading.setLayout(jpLoadingLayout);
        jpLoadingLayout.setHorizontalGroup(
            jpLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoadingLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jpLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblTextLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        jpLoadingLayout.setVerticalGroup(
            jpLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoadingLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTextLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );

        jPanel3.add(jpLoading, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMainLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel2))
                            .addGroup(jpMainLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(lblUf)
                                .addGap(7, 7, 7)
                                .addComponent(cbUfs, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUf)
                    .addComponent(cbUfs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jpMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMunicipiosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMunicipiosValueChanged

        // Pegar o index selecionado pelo evento não funciona muito bem 
        try {
            
            final int indexSelected = listMunicipios.getSelectedIndex();

            if ( listMunicipios.isSelectionEmpty() || indexSelected == -1 ) {
                return;
            }

            logger.log(Level.INFO, "listMunicipiosValueChanged [INDEX_SELECIONADO] {0}", indexSelected );
            
            onMunicipioSelected( municipios.get(indexSelected));
            
        } catch ( Exception e ) {
            logger.log(Level.SEVERE, "listMunicipiosValueChanged, Erro capturado [WHAT] {0}", e.getMessage());
        }
        
    }//GEN-LAST:event_listMunicipiosValueChanged

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // Pegar o index selecionado pelo evento não funciona muito bem 
        onEstadoChanged();
    }//GEN-LAST:event_btnSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbUfs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblTextLoading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane jlpInformations;
    private javax.swing.JPanel jpLoading;
    private javax.swing.JPanel jpMain;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblMunicipios;
    private javax.swing.JLabel lblUf;
    private javax.swing.JList<String> listMunicipios;
    // End of variables declaration//GEN-END:variables
}
